export const ASMA_UL_HUSNA = [
  { n: 1, arabic: "الرَّحْمَنُ", translit: "Ar-Rahmān", meaning: "O'ta mehribon" },
  { n: 2, arabic: "الرَّحِيمُ", translit: "Ar-Rahīm", meaning: "Rahmatli, o'ta rahmdil" },
  { n: 3, arabic: "الْمَلِكُ", translit: "Al-Malik", meaning: "Butun borliqning yakka hokimi va egasi" },
  { n: 4, arabic: "الْقُدُّوسُ", translit: "Al-Quddūs", meaning: "Barcha nuqsonlardan xoli va mutlaq pok" },
  { n: 5, arabic: "السَّلاَمُ", translit: "As-Salām", meaning: "Tinchlik va omonlik beruvchi" },
  { n: 6, arabic: "الْمُؤْمِنُ", translit: "Al-Mu'min", meaning: "Iymon va omonlik beruvchi" },
  { n: 7, arabic: "الْمُهَيْمِنُ", translit: "Al-Muhaymin", meaning: "Hamma narsani kuzatib, himoya qiluvchi" },
  { n: 8, arabic: "الْعَزِيزُ", translit: "Al-Azīz", meaning: "G'olib, qudratli va tengsiz" },
  { n: 9, arabic: "الْجَبَّارُ", translit: "Al-Jabbār", meaning: "O'z irodasini o'tkazuvchi va bandalar holini isloh qiluvchi" },
  { n: 10, arabic: "الْمُتَكَبِّرُ", translit: "Al-Mutakabbir", meaning: "Ulug'lik va buyuklik egasi" },
  { n: 11, arabic: "الْخَالِقُ", translit: "Al-Khāliq", meaning: "Barcha narsani yaratuvchi" },
  { n: 12, arabic: "الْبَارِئُ", translit: "Al-Bāri'", meaning: "Yaratuvi, bor qiluvchi" },
  { n: 13, arabic: "الْمُصَوِّرُ", translit: "Al-Musawvir", meaning: "Maxluqotlarga surat va shakl beruvchi" },
  { n: 14, arabic: "الْغَفَّارُ", translit: "Al-Ghaffār", meaning: "O'ta mag'firat qiluvchi, gunohlarni yopuvchi" },
  { n: 15, arabic: "الْقَهَّارُ", translit: "Al-Qahhār", meaning: "Barchani bo'ysundiruvchi, g'olib" },
  { n: 16, arabic: "الْوَهَّابُ", translit: "Al-Wahhāb", meaning: "Ko'plab ne'matlarni beminnat ehson qiluvchi" },
  { n: 17, arabic: "الرَّزَّاقُ", translit: "Ar-Razzāq", meaning: "Barcha maxluqotga rizq beruvchi" },
  { n: 18, arabic: "الْفَتَّاحُ", translit: "Al-Fattāh", meaning: "Eshiklarni, yo'llarni va qalblarni ochuvchi" },
  { n: 19, arabic: "الْعَلِيمُ", translit: "Al-Alīm", meaning: "Hamma narsani biluvchi" },
  { n: 20, arabic: "الْقَابِضُ", translit: "Al-Qābid", meaning: "Rizqlarni toraytiruvchi, jonlarni oluvchi" },
  { n: 21, arabic: "الْبَاسِطُ", translit: "Al-Bāsit", meaning: "Rizqlarni kengaytiruvchi, qalbni ochuvchi" },
  { n: 22, arabic: "الْخَافِضُ", translit: "Al-Khāfid", meaning: "Kofirlar va osiylarni darajasini pasaytiruvchi" },
  { n: 23, arabic: "الرَّافِعُ", translit: "Ar-Rāfi'", meaning: "Mo'minlarning darajasini ko'taruvchi" },
  { n: 24, arabic: "الْمُعِZُّ", translit: "Al-Mu'izz", meaning: "Aziz va ulug' qiluvchi" },
  { n: 25, arabic: "المُذِلُّ", translit: "Al-Mudhill", meaning: "Xor qiluvchi, pastga tushiruvchi" },
  { n: 26, arabic: "السَّمِيعُ", translit: "As-Samī'", meaning: "Sirlarni va oshkoralarni eshituvchi" },
  { n: 27, arabic: "الْبَصِيرُ", translit: "Al-Basīr", meaning: "Hamma narsani ko'ruvchi" },
  { n: 28, arabic: "الْحَكَمُ", translit: "Al-Hakam", meaning: "Mutlaq hakam va hukm qiluvchi" },
  { n: 29, arabic: "الْعَدْلُ", translit: "Al-Adl", meaning: "Mutlaq adolatli" },
  { n: 30, arabic: "اللَّطِيفُ", translit: "Al-Latīf", meaning: "O'ta lutfli, nozik va yashirin narsalarni biluvchi" },
  { n: 31, arabic: "الْخَبِيرُ", translit: "Al-Khabīr", meaning: "Hamma narsadan o'ta xabardor" },
  { n: 32, arabic: "الْحَلِيمُ", translit: "Al-Halīm", meaning: "G'azabi kelmaydigan, o'ta sabrli, muloyim" },
  { n: 33, arabic: "الْعَظِيمُ", translit: "Al-Azīm", meaning: "Mutlaq ulug', buyuk" },
  { n: 34, arabic: "الْغَفُورُ", translit: "Al-Ghafūr", meaning: "O'ta gunohlarni kechiruvchi" },
  { n: 35, arabic: "الشَّكُورُ", translit: "As-Shakūr", meaning: "Ozgina amalga ko'p mukofot beruvchi" },
  { n: 36, arabic: "الْعَلِيُّ", translit: "Al-Aliyy", meaning: "O'ta yuksak va oliy darajali" },
  { n: 37, arabic: "الْكَبِIRُ", translit: "Al-Kabīr", meaning: "Katta va eng buyuk" },
  { n: 38, arabic: "الْحَفِيظُ", translit: "Al-Hafīz", meaning: "Hamma narsani asraguvchi va himoya qiluvchi" },
  { n: 39, arabic: "المُقِيتُ", translit: "Al-Muqīt", meaning: "Moddiy va ma'naviy ozuqa beruvchi" },
  { n: 40, arabic: "الْحَسِيبُ", translit: "Al-Hasīb", meaning: "Kifoya qiluvchi, hisob-kitob qiluvchi" },
  { n: 41, arabic: "الْجَلِيلُ", translit: "Al-Jalīl", meaning: "Sifatlarida eng ulug'" },
  { n: 42, arabic: "الْكَرِيمُ", translit: "Al-Karīm", meaning: "O'ta saxovatli va beminnat beruvchi" },
  { n: 43, arabic: "الرَّقِيبُ", translit: "Ar-Raqīb", meaning: "Hammani doimiy nazorat qiluvchi" },
  { n: 44, arabic: "الْمُجِيبُ", translit: "Al-Mujīb", meaning: "Duolarni ijobat qiluvchi" },
  { n: 45, arabic: "الْوَاسِعُ", translit: "Al-Wāsi'", meaning: "Keng, fozil va marhamatli" },
  { n: 46, arabic: "الْحَكِيمُ", translit: "Al-Hakīm", meaning: "Hikmatli, barcha ishi to'g'ri bo'lgan" },
  { n: 47, arabic: "الْوَدُودُ", translit: "Al-Wadūd", meaning: "Yaxshi ko'ruvchi, sevikli" },
  { n: 48, arabic: "الْمَجِيدُ", translit: "Al-Majīd", meaning: "Shon-sharaf egasi, eng ulug'" },
  { n: 49, arabic: "الْبَاعِثُ", translit: "Al-Bā'ith", meaning: "O'liklarni qayta tiriltiruvchi" },
  { n: 50, arabic: "الشَّهِيدُ", translit: "As-Shahīd", meaning: "Har bir narsaga guvoh bo'luvchi" },
  { n: 51, arabic: "الْحَقُّ", translit: "Al-Haqq", meaning: "Sohib-haqiqat, barhayot" },
  { n: 52, arabic: "الْوَكِيلُ", translit: "Al-Wakīl", meaning: "Vakil qilinishga loyiq zot, ishonchli" },
  { n: 53, arabic: "الْقَوِيُّ", translit: "Al-Qawiyy", meaning: "Mutlaq quvvatli" },
  { n: 54, arabic: "الْمَتِينُ", translit: "Al-Matīn", meaning: "O'ta qudratli, baquvvat" },
  { n: 55, arabic: "الْوَلِيُّ", translit: "Al-Valiyy", meaning: "Mo'minlarga do'st va yordamchi" },
  { n: 56, arabic: "الْحَمِيدُ", translit: "Al-Hamīd", meaning: "Maqtovga loyiq mutlaq zot" },
  { n: 57, arabic: "الْمُحْصِي", translit: "Al-Muhsī", meaning: "Hamma narsaning hisobini biluvchi" },
  { n: 58, arabic: "الْمُبْدِئُ", translit: "Al-Mubdi'", meaning: "Boshlovchi, yo'qdan yaratuvchi" },
  { n: 59, arabic: "الْمُعِيدُ", translit: "Al-Mu'īd", meaning: "Yana qaytaruvchi, hayot beruvchi" },
  { n: 60, arabic: "الْمُحْيِي", translit: "Al-Muhyī", meaning: "Hayot beruvchi, tiriltiruvchi" },
  { n: 61, arabic: "الْمُمِيتُ", translit: "Al-Mumīt", meaning: "O'ldiruvchi, hayotni oluvchi" },
  { n: 62, arabic: "الْحَيُّ", translit: "Al-Hayy", meaning: "Abadiy barhayot, tirik" },
  { n: 63, arabic: "الْقَيُّومُ", translit: "Al-Qayyūm", meaning: "O'z-o'zidan turuvchi, borliqni saqlovchi" },
  { n: 64, arabic: "الْوَاجِدُ", translit: "Al-Vājid", meaning: "Istaganchasini yaratuvchi va topuvchi" },
  { n: 65, arabic: "الْمَاجِدُ", translit: "Al-Mājid", meaning: "Oliy darajali, saxovatli" },
  { n: 66, arabic: "الْوَاحِدُ", translit: "Al-Vāhid", meaning: "Yagona va yakka" },
  { n: 67, arabic: "الصَّمَدُ", translit: "As-Samad", meaning: "Hech narsaga muhtoj bo'lmagan, barcha unga muhtoj" },
  { n: 68, arabic: "الْقَادِرُ", translit: "Al-Qādir", meaning: "Cheksiz qudrat egasi" },
  { n: 69, arabic: "الْمُقْتَدِرُ", translit: "Al-Muqtadir", meaning: "Mutlaq hukmronlik qiluvchi" },
  { n: 70, arabic: "الْمُقَدِّمُ", translit: "Al-Muqaddim", meaning: "Istaganchasini oldinga suruvchi" },
  { n: 71, arabic: "الْمُؤَخِّرُ", translit: "Al-Mu'akhkhir", meaning: "Istaganchasini orqaga suruvchi" },
  { n: 72, arabic: "الأوَّلُ", translit: "Al-Avval", meaning: "Boshlanishi bo'lmagan zot" },
  { n: 73, arabic: "الآخِرُ", translit: "Al-Ākhir", meaning: "Oxiri bo'lmagan, abadiy" },
  { n: 74, arabic: "الظَّاهِرُ", translit: "Az-Zāhir", meaning: "Borligi ochiq-oydin bo'lgan" },
  { n: 75, arabic: "الْبَاطِنُ", translit: "Al-Bātin", meaning: "Sirlarni biluvchi, ko'rinmaydigan" },
  { n: 76, arabic: "الْوَالِي", translit: "Al-Vālī", meaning: "Hukmdor va boshqaruvchi" },
  { n: 77, arabic: "الْمُتَعَالِي", translit: "Al-Muta'ālī", meaning: "Nuqsonlardan o'ta oliy" },
  { n: 78, arabic: "الْبَرُّ", translit: "Al-Barr", meaning: "Ezgulik va ehson qiluvchi" },
  { n: 79, arabic: "التَّوَّابُ", translit: "At-Tavvāb", meaning: "Tavbalarni qabul qiluvchi" },
  { n: 80, arabic: "الْمُنْتَقِمُ", translit: "Al-Muntaqim", meaning: "Zolimlardan intiqom oluvchi" },
  { n: 81, arabic: "العَفُوُw", translit: "Al-Afuvv", meaning: "O'ta afv qiluvchi, gunohlarni o'chiruvchi" },
  { n: 82, arabic: "الرَّؤُوفُ", translit: "Ar-Ra'ūf", meaning: "O'ta rahmdil, lutfli" },
  { n: 83, arabic: "مَالِكُ الْمُلْكِ", translit: "Mālik-ul-Mulk", meaning: "Mulkning mutlaq egasi" },
  { n: 84, arabic: "ذُو الْجَلاَلِ وَالإِكْرَامِ", translit: "Dhul-Jalāli-val-Ikrām", meaning: "Ulug'lik, buyuklik va ehson egasi" },
  { n: 85, arabic: "الْمُقْسِطُ", translit: "Al-Muqsit", meaning: "Odil, adolat pesha" },
  { n: 86, arabic: "الْجَامِعُ", translit: "Al-Jāmi'", meaning: "Barchani qiyomat kuni jamlovchi" },
  { n: 87, arabic: "الْغَنِيُّ", translit: "Al-Ghaniyy", meaning: "G'ani, hech narsaga muhtoj emas" },
  { n: 88, arabic: "الْمُغْنِي", translit: "Al-Mughnī", meaning: "Ehtiyojlarni qondiruvchi, boy qiluvchi" },
  { n: 89, arabic: "الْمَانِعُ", translit: "Al-Māni'", meaning: "Xohlagan narsasini to'suvchi va qaytaruvchi" },
  { n: 90, arabic: "الضَّارُّ", translit: "Ad-Dārr", meaning: "Xohlaganiga zarar yetkazuvchi" },
  { n: 91, arabic: "النَّافِعُ", translit: "An-Nāfi'", meaning: "Xohlaganiga foyda yetkazuvchi" },
  { n: 92, arabic: "النُّورُ", translit: "An-Nūr", meaning: "Nurlantiruvchi, butun borliqni yorituvchi" },
  { n: 93, arabic: "الْهَادِي", translit: "Al-Hādī", meaning: "To'g'ri yo'lga boshlovchi, hidoyat beruvchi" },
  { n: 94, arabic: "الْبَدِيعُ", translit: "Al-Badī'", meaning: "Mislsiz, yangilik yaratuvchi" },
  { n: 95, arabic: "الْبَاقِي", translit: "Al-Bāqī", meaning: "Abadiy qoluvchi" },
  { n: 96, arabic: "الْوَارِثُ", translit: "Al-Vārith", meaning: "Mulkning haqiqiy vorisi" },
  { n: 97, arabic: "الرَّشِيدُ", translit: "Ar-Rashīd", meaning: "To'g'ri yo'l ko'rsatuvchi" },
  { n: 98, arabic: "الصَّبُورُ", translit: "As-Sabūr", meaning: "O'ta sabrli, jazolashga shoshilmaydigan" },
  { n: 99, arabic: "الله", translit: "Alloh", meaning: "Yagona, ibodatga loyiq iloh" }
];
